service:
  type: LoadBalancer

chromadb:
  isPersistent: true
  persistDirectory: /data
  data:
    storageClass: truenas-nfs
  telemetry:
    enabled: true
    serviceName: ChromaDB
    endpoint: grpc://otelcol.jds.net:4317
