server:
  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/data"
    storageClass: "truenas-nfs"
    accessMode: ReadWriteOnce
  dev:
    enabled: true
ui:
  enabled: true
  serviceType: "LoadBalancer"
  loadBalancerIP: "192.168.1.248"
