apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-vault
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  server: 192.168.1.21
  path: /mnt/pool/vault-data
  onDelete: retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-vault
  nfs:
    server: 192.168.1.21
    path: /mnt/pool/vault-data
