apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: monitoring
spec:
  selector:
    app: clickhouse
  ports:
  - name: client
    port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: clickhouse-ui
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.250
  selector:
    app: clickhouse
  ports:
  - name: http
    port: 80
    targetPort: 8123
