apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-ingress-config
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      influxdb:
        endpoint: 0.0.0.0:8086
    
    processors:
      batch:
        timeout: 5s
        send_batch_size: 10000
      cumulativetodelta: {}
    
    exporters:
      clickhouse:
        endpoint: "tcp://clickhouse:9000?username=admin&password=admin"
        username: admin
        password: admin
        database: otel
        timeout: 10s
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        metrics_table_name: otel_metrics
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
      debug: {}
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse, debug]
        metrics:
          receivers: [influxdb, otlp]
          processors: [batch, cumulativetodelta]
          exporters: [clickhouse, debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse, debug]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol-ingress
  namespace: monitoring
  labels:
    app: otelcol-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol-ingress
  template:
    metadata:
      labels:
        app: otelcol-ingress
    spec:
      volumes:
      - name: otelcol-config
        configMap:
          name: otelcol-ingress-config
      containers:
      - name: otelcol-ingress
        image: otel/opentelemetry-collector-contrib:0.120.0
        args:
        - "--config=/etc/otelcol/config.yaml"
        volumeMounts:
        - name: otelcol-config
          mountPath: /etc/otelcol
        ports:
        - containerPort: 4317
---
apiVersion: v1
kind: Service
metadata:
  name: otelcol-ingress
  namespace: monitoring
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.251
  selector:
    app: otelcol-ingress
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317 
  - name: influxdb
    port: 8086
    targetPort: 8086
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otelcol-ingress
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/otelcol-ingress
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
