apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otelcol-ingress
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ingress-telemetry
    server: https://kubernetes.default.svc
  sources:
  - chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.116.0
    helm:
      valueFiles:
        - $values/apps/otelcol-ingress/values.yaml
  - path: apps/otelcol-ingress
    ref: values
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
    selfHeal: true
    syncOptions:
    - CreateNamespace=true
