apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/destination-namespace: "monitoring"
spec:
  project: default
  sources:
  - chart: opentelemetry-kube-stack
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.4.4
    helm:
      valueFiles:
        - $values/apps/otelcol-ingress/values.yaml
  - path: apps/otelcol-ingress
    ref: values
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
