apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollyman
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/destination-namespace: "monitoring"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/jSwanson99/helm.git
    targetRevision: master
    path: ./charts/ollyman
    helm:
      valueFiles:
        - $values/config/ollyman/values.yaml
  - path: config/ollyman
    ref: values
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
