apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/destination-namespace: "cert-manager"
spec:
  project: default
  sources:
  - chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.1
    helm:
      values: |
        installCRDs: true
  - path: config/cert-manager
    ref: values
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
