apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chromadb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/destination-namespace: "devtools"
spec:
  destination:
    namespace: devtools
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: chromadb
    repoURL: https://amikos-tech.github.io/chromadb-chart
    targetRevision: 0.1.24
    helm:
      valueFiles:
        - $values/config/vectordb/values.yaml
  - path: config/vectordb
    ref: values
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
