replicas: 1

autoscaling:
  enabled: false

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: "192.168.1.252"
  port: 80
  targetPort: 3000

adminUser: admin
adminPassword: admin

persistence:
  enabled: true
  storageClassName: truenas-nfs
  
initChownData:
  enabled: false
  securityContext:
    runAsUser: 472
    runAsGroup: 472

securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472
