replicas: 1

autoscaling:
  enabled: false

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 3000

adminUser: admin
adminPassword: admin

persistence:
  enabled: true
  storageClassName: truenas-nfs

initChownData:
  enabled: false
  securityContext:
    runAsUser: 472
    runAsGroup: 472

securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

env:
  GF_FEATURE_TOGGLES_ENABLE: "dashboardScene,dashboardNewLayouts,kubernetesDashboards"
  GF_PLUGINS_PREINSTALL: "grafana-clickhouse-datasource"
