apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor
  namespace: kube-system-ancillary
spec:
  parentRefs:
  - name: cilium
    namespace: default
    sectionName: https
  hostnames:
  - harbor.jds.net
  rules:
  - matches:
    - path:
        value: "/"
        type: PathPrefix
    backendRefs:
    - name: harbor
      port: 80
