mode: daemonset
presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: false
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.79.0
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  exporters:
    logging:
      verbosity: detailed
  processors:
    batch:
      timeout: 10s
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging]
