apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    path: config/minio
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-tenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  dependsOn:
  - name: minio-operator
    namespace: argocd
