apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/destination-namespace: "monitoring"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.9.0
    helm:
      valueFiles:
        - $values/config/grafana/values.yaml
  - path: config/grafana
    ref: values
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
