adminPassword: admin123

persistence:
  enabled: true
  size: 10Gi
  
# datasources:
#  datasources.yaml:

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  annotations: {}
