replicas: 1

autoscaling:
  enabled: false

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: "192.168.1.252"
  port: 80
  targetPort: 3000

adminUser: admin
adminPassword: admin

#persistence:
#  type: pvc
#  enabled: true
#  size: 10Gi
