apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-gateway-config
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      influxdb:
        endpoint: 0.0.0.0:8086
      zipkin:
        endpoint: 0.0.0.0:9411
      syslog:
        udp:
          listen_address: "0.0.0.0:1514"
          add_attributes: true
        protocol: rfc5424
      prometheus:
        config:
          scrape_configs:
            - job_name: 'cilium-operator'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  regex: cilium-operator
                  action: keep
            - job_name: 'envoy'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  regex: cilium
                  action: keep
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: keep
                  regex: 9964

    processors:
      logdedup: {}
      batch:
        send_batch_size: 8192
        timeout: 5s
      cumulativetodelta: {}
      transform:
        metric_statements:
          - context: datapoint
            statements:
              - set(resource.attributes["service.name"], datapoint.attributes["host"]) where resource.attributes["service.name"] == nil
        log_statements:
          - statements:
              - set(resource.attributes["service.name"], log.attributes["hostname"]) where resource.attributes["service.name"] == nil
              - set(log.body, Trim(log.attributes["message"])) where resource.attributes["service.name"] == "vyos"
              - set(log.cache["msg"], log.body) where resource.attributes["service.name"] == "coredns"
              - set(log.body, log.cache["msg"]["MESSAGE"]) where resource.attributes["service.name"] == "coredns"
              - set(log.attributes, ExtractPatterns(log.body, "\\[(?P<level>\\S+)\\] (?P<client_ip>[^:]+):(?P<client_port>\\d+) - (?P<query_id>\\S+) \"(?P<type>\\S+) (?P<direction>\\S+) (?P<name>\\S+) (?P<protocol>\\S+) (?P<request_size>\\d+) (?P<dnssec_ok>\\S+) (?P<bufsize>\\d+)\" (?P<rcode>\\S+) (?P<flags>[^\\s]+) (?P<response_size>\\d+) (?P<duration_seconds>[\\d\\.]+s)")) where resource.attributes["service.name"] == "coredns"

    exporters:
      clickhouse:
        endpoint: "tcp://clickhouse:9000?compress=lz4&async_insert=1"
        create_schema: true
        username: admin
        password: admin
        sending_queue:
          queue_size: 1000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s

    service:
      pipelines:
        traces:
          receivers: [zipkin, otlp]
          processors: [transform, batch]
          exporters: [clickhouse]
        metrics:
          receivers: [influxdb, otlp]
          processors: [transform, cumulativetodelta, batch]
          exporters: [clickhouse]
        logs:
          receivers: [otlp, syslog]
          processors: [transform, logdedup, batch]
          exporters: [clickhouse]
