apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-gateway-config
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      influxdb:
        endpoint: 0.0.0.0:8086
      zipkin:
        endpoint: 0.0.0.0:9411
      syslog:
        udp:
          listen_address: "0.0.0.0:1514"
          add_attributes: true
        protocol: rfc5424
      prometheus:
        config:
          scrape_configs:
            - job_name: 'cilium-operator'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  regex: cilium-operator
                  action: keep
            - job_name: 'envoy'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  regex: cilium
                  action: keep
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: keep
                  regex: 9964

    processors:
      logdedup: {}
      batch: {}
      cumulativetodelta: {}
      transform:
        metric_statements:
          - context: datapoint
            statements:
              - set(resource.attributes["service.name"], datapoint.attributes["host"]) where resource.attributes["service.name"] == nil
        log_statements:
          - statements:
              - set(resource.attributes["service.name"], log.attributes["hostname"]) where resource.attributes["service.name"] == nil
              - set(log.body, Trim(log.attributes["message"])) where resource.attributes["service.name"] == "vyos"

    exporters:
      clickhouse:
        endpoint: "tcp://clickhouse:9000"
        create_schema: true
        username: admin
        password: admin

    service:
      pipelines:
        traces:
          receivers: [zipkin, otlp]
          processors: [transform, batch]
          exporters: [clickhouse]
        metrics:
          receivers: [influxdb, otlp]
          processors: [transform, cumulativetodelta, batch]
          exporters: [clickhouse]
        logs:
          receivers: [otlp, syslog]
          processors: [transform, logdedup, batch]
          exporters: [clickhouse]
