apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol-gateway
  namespace: monitoring
  labels:
    app: otelcol-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol-gateway
  template:
    metadata:
      labels:
        app: otelcol-gateway
    spec:
      volumes:
      - name: otelcol-config
        configMap:
          name: otelcol-gateway-config
      containers:
      - name: otelcol-gateway
        image: otel/opentelemetry-collector-contrib:0.121.0
        args:
        - "--config=/etc/otelcol/config.yaml"
        volumeMounts:
        - name: otelcol-config
          mountPath: /etc/otelcol
        ports:
        - containerPort: 4317
