apiVersion: v1
kind: Service
metadata:
  name: otelcol-ingress
  namespace: monitoring
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.251
  selector:
    app: otelcol-ingress
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317 
  - name: influxdb
    port: 8086
    targetPort: 8086
