apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: monitoring
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:25.1.5
        ports:
        - containerPort: 9000
        - containerPort: 8123
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              name: clickhouse-auth
              key: username
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-auth
              key: password
      volumeMounts:
      - name: clickhouse-data
        mountPath: /var/lib/clickhouse
    volumes:
      - name: clickhouse-data
        persistentVolumeClaim:
          claimName: clickhouse-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: monitoring
spec:
  selector:
    app: clickhouse
  ports:
  - name: client
    port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: clickhouse-ui
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.250
  selector:
    app: clickhouse
  ports:
  - name: http
    port: 80
    targetPort: 8123
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/clickhouse
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
  namespace: monitoring
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  nfs:
    path: /mnt/pool/clickhouse-data
    server: 192.168.1.21
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: monitoring
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
