apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  project: default
  source:
    path: apps/clickhouse
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  defaults:
    templates:
      podTemplate: clickhouse-template
      dataVolumeClaimTemplate: clickhouse-vc
      logVolumeClaimTemplate: clickhouse-vc
  
  configuration:
    clusters:
      - name: default
        layout:
          shardsCount: 1
          replicasCount: 1
  
  templates:
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.8
              resources:
                requests:
                  memory: 2Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 1000m

    volumeClaimTemplates:
      - name: clickhouse-vc
        persistentVolumeClaim:
          claimName: clickhouse-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: truenas-nfs
          resources:
            requests:
              storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  nfs:
    path: /mnt/pool/clickhouse-data
    server: 192.168.1.21
