apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  project: default
  source:
    path: apps/clickhouse
    repoURL: https://github.com/jSwanson99/homelab-gitops.git
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
  namespace: clickhouse
  finalizers:
    - finalizer.clickhouseinstallation.altinity.com
spec:
  defaults:
    templates:
      podTemplate: clickhouse-template
  
  configuration:
    settings:
      http_port: 8124
      tcp_port: 9001
      interserver_http_port: 9010
    clusters:
      - name: default
        layout:
          shardsCount: 1
          replicasCount: 1
  
  templates:
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.8
              resources:
                requests:
                  memory: 2Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 1000m
              ports:
                - name: http
                  containerPort: 8124
                - name: tcp
                  containerPort: 9001
                - name: interserver
                  containerPort: 9010
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server

    volumeClaimTemplates:
      - name: data-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          volumeName: clickhouse-pv 
          storageclassname: truenas-nfs
      - name: log-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          volumeName: clickhouse-pv 
          storageclassname: truenas-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
  labels:
    app: clickhouse-storage
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  nfs:
    path: /mnt/pool/clickhouse-data
    server: 192.168.1.21
