apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  source:
    repoURL: https://docs.altinity.com/clickhouse-operator/
    chart: altinity-clickhouse-operator
    name: clickhouse-operator
    targetRevision: 0.24.0
  syncPolicy:
    automations:
      - selfHeal: true
    syncOptions:
      - CreateNamespace=true
