apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-tools
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/destination-namespace: "monitoring"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: kubernetes-dashboard
    repoURL: https://kubernetes.github.io/dashboard/
    targetRevision: 7.13.0
    helm:
      valuesObject:
        kong:
          proxy:
            type: LoadBalancer
  - chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.2
    helm:
      valuesObject:
        defaultArgs:
          - --cert-dir=/tmp
          - --kubelet-preferred-address-types=Hostname,InternalIP,ExternalIP
          - --kubelet-use-node-status-port
          - --metric-resolution=15s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
