apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: default
spec:
  secretName: gateway-cert-tls
  issuerRef:
    name: kubernetes-ca-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.jds.net"
  - "jds.net"
