apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble
  namespace: monitoring
spec:
  parentRefs:
  - name: cilium
    namespace: kube-system
  hostnames:
  - hubble.jds.net
  rules:
  - matches:
    - path:
        value: "/"
        type: PathPrefix
    backendRefs:
    - name: hubble-ui
      port: 8081
