apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-pvc
  namespace: matrix
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
